description: 'Mobile and desktop app for FRC scouting'
name: 'scouting_app'
version: '1.0.0+1'
dependencies:
  cupertino_icons: '^0.1.3'
  flutter_staggered_animations: '^0.1.2'
  shared_preferences: '^0.5.6+3'
  provider: '>=4.0.0 <5.0.0'
  flutter:
    sdk: flutter
dev_dependencies:
  local_google_fonts: '^1.0.8'
  flutter_test:
    sdk: flutter
  import_sorter: ^3.0.6
environment:
  sdk: '>=2.7.0 <3.0.0'
flutter:
  fonts:
    - family: 'Nunito'
      fonts:
        - asset: 'assets/fonts/googleFonts/Nunito/Nunito-200i.ttf'
          style: 'italic'
          weight: 200
        - asset: 'assets/fonts/googleFonts/Nunito/Nunito-300i.ttf'
          style: 'italic'
          weight: 300
        - asset: 'assets/fonts/googleFonts/Nunito/Nunito-400i.ttf'
          style: 'italic'
          weight: 400
        - asset: 'assets/fonts/googleFonts/Nunito/Nunito-600i.ttf'
          style: 'italic'
          weight: 600
        - asset: 'assets/fonts/googleFonts/Nunito/Nunito-700i.ttf'
          style: 'italic'
          weight: 700
        - asset: 'assets/fonts/googleFonts/Nunito/Nunito-800i.ttf'
          style: 'italic'
          weight: 800
        - asset: 'assets/fonts/googleFonts/Nunito/Nunito-900i.ttf'
          style: 'italic'
          weight: 900
        - asset: 'assets/fonts/googleFonts/Nunito/Nunito-200.ttf'
          weight: 200
        - asset: 'assets/fonts/googleFonts/Nunito/Nunito-300.ttf'
          weight: 300
        - asset: 'assets/fonts/googleFonts/Nunito/Nunito-400.ttf'
          weight: 400
        - asset: 'assets/fonts/googleFonts/Nunito/Nunito-600.ttf'
          weight: 600
        - asset: 'assets/fonts/googleFonts/Nunito/Nunito-700.ttf'
          weight: 700
        - asset: 'assets/fonts/googleFonts/Nunito/Nunito-800.ttf'
          weight: 800
        - asset: 'assets/fonts/googleFonts/Nunito/Nunito-900.ttf'
          weight: 900
    - family: 'Raleway'
      fonts:
        - asset: 'assets/fonts/googleFonts/Raleway/Raleway-100i.ttf'
          style: 'italic'
          weight: 100
        - asset: 'assets/fonts/googleFonts/Raleway/Raleway-200i.ttf'
          style: 'italic'
          weight: 200
        - asset: 'assets/fonts/googleFonts/Raleway/Raleway-300i.ttf'
          style: 'italic'
          weight: 300
        - asset: 'assets/fonts/googleFonts/Raleway/Raleway-400i.ttf'
          style: 'italic'
          weight: 400
        - asset: 'assets/fonts/googleFonts/Raleway/Raleway-500i.ttf'
          style: 'italic'
          weight: 500
        - asset: 'assets/fonts/googleFonts/Raleway/Raleway-600i.ttf'
          style: 'italic'
          weight: 600
        - asset: 'assets/fonts/googleFonts/Raleway/Raleway-700i.ttf'
          style: 'italic'
          weight: 700
        - asset: 'assets/fonts/googleFonts/Raleway/Raleway-800i.ttf'
          style: 'italic'
          weight: 800
        - asset: 'assets/fonts/googleFonts/Raleway/Raleway-900i.ttf'
          style: 'italic'
          weight: 900
        - asset: 'assets/fonts/googleFonts/Raleway/Raleway-100.ttf'
          weight: 100
        - asset: 'assets/fonts/googleFonts/Raleway/Raleway-200.ttf'
          weight: 200
        - asset: 'assets/fonts/googleFonts/Raleway/Raleway-300.ttf'
          weight: 300
        - asset: 'assets/fonts/googleFonts/Raleway/Raleway-400.ttf'
          weight: 400
        - asset: 'assets/fonts/googleFonts/Raleway/Raleway-500.ttf'
          weight: 500
        - asset: 'assets/fonts/googleFonts/Raleway/Raleway-600.ttf'
          weight: 600
        - asset: 'assets/fonts/googleFonts/Raleway/Raleway-700.ttf'
          weight: 700
        - asset: 'assets/fonts/googleFonts/Raleway/Raleway-800.ttf'
          weight: 800
        - asset: 'assets/fonts/googleFonts/Raleway/Raleway-900.ttf'
          weight: 900
  uses-material-design: true
google_fonts:
  fonts:
    - Nunito
    - 'Raleway'
import_sorter:
  emojis: true
