name: scouting_app
description: Mobile and desktop app for FRC scouting
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_staggered_animations: ^0.1.2
  simple_animations: ^1.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/regular.ttf
        - asset: assets/fonts/Nunito/italic.ttf
          style: italic
        - asset: assets/fonts/Nunito/bold.ttf
          weight: 700
  assets:
    - assets/images/
